# Generated by Django 5.1.5 on 2025-05-18 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapePhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Financier', 'Financier'), ('Technique', 'Technique'), ('Logistique', 'Logistique')], max_length=100)),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhaseProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Decaissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomEtape', models.CharField(max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('dateDecaissement', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('actualDeliverables', models.TextField(blank=True, null=True)),
                ('document', models.FileField(upload_to='livrables/')),
                ('budgetRestant', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('etape', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decaissements', to='projet.etapephase')),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decaissements', to='projet.phaseprojet')),
            ],
        ),
        migrations.CreateModel(
            name='Livrable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(default='', upload_to='livrables/')),
                ('description', models.TextField(blank=True, null=True)),
                ('decaissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livrables', to='projet.decaissement')),
            ],
        ),
        migrations.AddField(
            model_name='etapephase',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='projet.phaseprojet'),
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True, verbose_name='Nom du Projet')),
                ('typeProjet', models.CharField(default='route', max_length=50, verbose_name='Type de Projet')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Budget (FCFA)')),
                ('dateDebut', models.DateField(verbose_name='Date de Début')),
                ('dateFin', models.DateField(blank=True, null=True, verbose_name='Date de Fin Prévue')),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('attente_financement', 'En attente de financement')], default='planifie', max_length=50, verbose_name='Statut du Projet')),
                ('region', models.CharField(max_length=100, verbose_name='Région')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('objectifs', models.TextField(verbose_name='Objectifs du Projet')),
                ('description', models.TextField(verbose_name='Description Détaillée')),
                ('prestataire', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='prestataire', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorite', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='phaseprojet',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='projet.projet'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('send_date', models.DateTimeField(auto_now_add=True)),
                ('sent_to', models.CharField(max_length=200)),
                ('platform', models.CharField(choices=[('Facebook', 'Facebook'), ('SMS', 'SMS')], max_length=100)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='projet.projet')),
            ],
        ),
        migrations.AddField(
            model_name='decaissement',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decaissements', to='projet.projet'),
        ),
        migrations.CreateModel(
            name='CitizenReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizen_name', models.CharField(max_length=200)),
                ('report_date', models.DateField(auto_now_add=True)),
                ('report_text', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='reports/')),
                ('status', models.CharField(choices=[('New', 'New'), ('Reviewed', 'Reviewed'), ('Resolved', 'Resolved')], max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='projet.projet')),
            ],
        ),
        migrations.CreateModel(
            name='ActeursImpliques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partenaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Partenaire', to='projet.partenaire')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Acteurs', to='projet.projet')),
            ],
        ),
    ]
