# Generated by Django 5.1.5 on 2025-03-29 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizen_name', models.CharField(max_length=200)),
                ('report_date', models.DateField(auto_now_add=True)),
                ('report_text', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='reports/')),
                ('status', models.CharField(choices=[('New', 'New'), ('Reviewed', 'Reviewed'), ('Resolved', 'Resolved')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Decaissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomEtape', models.CharField(max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('dateDecaissement', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('actualDeliverables', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DetailsProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectifs', models.TextField(verbose_name='Objectifs du Projet')),
                ('description', models.TextField(verbose_name='Description Détaillée')),
            ],
        ),
        migrations.CreateModel(
            name='Localisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100, verbose_name='Région')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('send_date', models.DateTimeField(auto_now_add=True)),
                ('sent_to', models.CharField(max_length=200)),
                ('platform', models.CharField(choices=[('Facebook', 'Facebook'), ('SMS', 'SMS')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Financier', 'Financier'), ('Technique', 'Technique'), ('Logistique', 'Logistique')], max_length=100)),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True, verbose_name='Nom du Projet')),
                ('typeProjet', models.CharField(choices=[('infrastructure', 'Infrastructure'), ('energie', 'Énergie'), ('sante', 'Santé'), ('education', 'Éducation'), ('transport', 'Transport'), ('autre', 'Autre')], max_length=50, verbose_name='Type de Projet')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Budget (FCFA)')),
                ('dateDebut', models.DateField(verbose_name='Date de Début')),
                ('dateFin', models.DateField(blank=True, null=True, verbose_name='Date de Fin Prévue')),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('attente_financement', 'En attente de financement')], default='planifie', max_length=50, verbose_name='Statut du Projet')),
            ],
        ),
        migrations.CreateModel(
            name='ActeursImpliques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partenaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Partenaire', to='projet.partenaire')),
            ],
        ),
    ]
