# Generated by Django 5.1.5 on 2025-06-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True, verbose_name='Nom du Projet')),
                ('code_projet', models.CharField(max_length=100, unique=True, verbose_name='Code du Projet')),
                ('debut_troncon', models.CharField(max_length=255, verbose_name='Début du Tronçon')),
                ('fin_troncon', models.CharField(max_length=255, verbose_name='Fin du Tronçon')),
                ('region', models.CharField(max_length=100, verbose_name='Région principale')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('type_travaux', models.CharField(choices=[('rehabilitation', 'Réhabilitation'), ('construction', 'Construction nouvelle'), ('bitumage', 'Bitumage'), ('entretien', 'Entretien'), ('elargissement', 'Élargissement')], max_length=50)),
                ('longueur_troncon', models.DecimalField(decimal_places=2, help_text='En kilomètres', max_digits=6)),
                ('largeur_chaussee', models.DecimalField(decimal_places=2, help_text='En mètres', max_digits=4)),
                ('dateDebut', models.DateField(verbose_name='Date de Début')),
                ('dateFin', models.DateField(blank=True, null=True, verbose_name='Date de Fin Prévue')),
                ('type_revetement', models.CharField(choices=[('bitume', 'Bitume'), ('laterite', 'Latérite'), ('beton', 'Béton')], max_length=50)),
                ('normes_techniques', models.TextField(verbose_name='Normes Techniques')),
                ('maitre_ouvrage', models.CharField(max_length=255, verbose_name='Maître d’Ouvrage')),
                ('bureau_controle', models.CharField(max_length=255, verbose_name='Bureau de Contrôle')),
                ('bailleurs', models.TextField(verbose_name='Bailleur(s) de Fonds')),
                ('prestataire', models.TextField(max_length=50)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Budget Global (FCFA)')),
                ('description', models.TextField(verbose_name='Description Détaillée')),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('suspendu', 'Suspendu')], default='planifie', max_length=50, verbose_name='Statut')),
                ('plan_directeur', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('budget_detaille', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('rapport_avancement', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('contrat_principal', models.FileField(blank=True, null=True, upload_to='documents/')),
            ],
        ),
    ]
