# Generated by Django 5.1.5 on 2025-05-28 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livrable',
            name='decaissement',
        ),
        migrations.AddField(
            model_name='etapephase',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=60000, max_digits=15),
        ),
        migrations.AddField(
            model_name='livrable',
            name='etape',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='livrables', to='projet.etapephase'),
        ),
        migrations.DeleteModel(
            name='Decaissement',
        ),
    ]
