# Generated by Django 5.1.5 on 2025-06-11 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='rapport_avancement',
        ),
    ]
