# Generated by Django 5.1.5 on 2025-05-02 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='decaissement',
            name='budgetRestant',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15),
        ),
        migrations.AlterField(
            model_name='decaissement',
            name='actualDeliverables',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Livrable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='livrables/')),
                ('description', models.TextField(blank=True, null=True)),
                ('decaissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livrables', to='projet.decaissement')),
            ],
        ),
    ]
