# Generated by Django 5.1.5 on 2025-05-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0003_decaissement_budgetrestant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='decaissement',
            name='document',
            field=models.FileField(default=1, upload_to='livrables/'),
            preserve_default=False,
        ),
    ]
