# Generated by Django 5.1.5 on 2025-06-12 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0003_remove_projet_rapport_avancement'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhaseProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('dateDebut', models.DateField()),
                ('dateFin', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, default=60000, max_digits=15)),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('suspendu', 'Suspendu')], default='planifie', max_length=50, verbose_name='Statut')),
                ('description', models.TextField(blank=True, null=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='projet.projet')),
            ],
        ),
    ]
